### ISSUE TITLE
`${workspaceFolder}` variable returns empty string when viewing file outside of workspace

### ISSUE THREAD

**Issue by DanStevens** [edonet/vscode-command-runner#10]
I've just started using the _Run Command_ extension and I'm trying out the example, which is as follows:

```json
{
    "commands": {
        "echo workspaceFolder": "echo ${workspaceFolder}",
        "echo file": "echo ${file}"
    }
}
```

However, it doesn't seem to work. Running this command results in the following output:

    echo

It appears the `${workspaceFolder}` variable is returning empty string.

After further investigation, I've observed that `${workspaceFolder}` is empty when the active tab within the editor is is displaying a file outside of the workspace. I'm not sure if this is intentional, but in view the is a bug - `${workspaceFolder}` should be set to the path of the currently loaded workspace or folder, regardless of the active editor tab.

**Steps to reproduce**:

1. Within Visual Studio Code, open the `settings.json` settings file.
2. Set the `command-runner.commands` option so that it matches the above and save.
3. Open a folder or workspace.
4. Open a file within the folder/workspace and ensure it is the active tab.
5. Press <kbd>F1</kbd> and enter `Run Command` and press <kbd>Enter</kbd>
6. Select the entry `echo workspacefolder`
7. Observe the _Terminal_ window - it should output:

```
    $ echo c:\Users\dstevens\myprojects\myworkspace
     c:Usersdstevensmyprojectsmyworkspace
```

8. Select a file outside of the workspace (e.g. the `settings.json` file from step 1).
9. Press <kbd>F1</kbd> and enter `Run Command` and press <kbd>Enter</kbd>
10. Select the entry `echo workspacefolder`
11. Observe the _Terminal_ window - it should output the same as step 7, but instead it outputs:

`     echo`

**Comment by edonet** [comment]
Thanks for your issue! the problem will fix on v0.0.112. enjoy it!
