### ISSUE TITLE
Do not show terminal window when running command

### ISSUE THREAD

**Issue by ragurney** [edonet/vscode-command-runner#17]
Is there a way to stop the terminal window popping up when running a command?

**Comment by danigosa** [comment]
This is really a must-have for instance for external formatters, it is pretty annoying

**Comment by edonet** [comment]
Since commands must be run using the terminal, there is currently no way to prevent the terminal from popping up. Subsequent commands may be run in nodejs, which is possible, but may not be able to achieve complex scenarios.

**Comment by ragurney** [comment]
Is [this commit](https://github.com/edonet/vscode-command-runner/commit/a89d8a8d19ad0cc66b41d65d1bfc5ed4bf70f377) relevant?

**Comment by edonet** [comment]
Yes, this code provides a way to control whether the terminal is displayed when the command is executed. But at present, the configuration can only be passed in when it is called by `executeCommand`, and no more friendly interactive method is provided.

**Comment by mn4367** [comment]
If you append

```
${command:workbench.action.togglePanel}
```

to a command or keybinding it doesn't show the terminal (for whatever reasons).

VS Code 1.46.1 Mac.

**Comment by edonet** [comment]
Added `command-runner.terminal.autoFocus` option for focus the terminal when run command.
