### ISSUE TITLE
not enter command on last focus windows terminal

### ISSUE THREAD

**Issue by mean-cj** [edonet/vscode-command-runner#19]
Hello @edonet

Thank you for your project

When i split terminal or new terminal.
after Command Runner, not enter command text on last focus terminal

Thank you.

![Video_2020-04-18_174354](https://user-images.githubusercontent.com/1191385/79635695-90a78380-819c-11ea-8aa8-2a79021bb174.gif)

**Comment by edonet** [comment]
Maybe you should let me know which terminal you want the command to run on.

**Comment by edonet** [comment]
Set the terminal name by `command-runner.terminal.name` for command.
