### ISSUE TITLE
Keyboard shortcuts not working VSCode 1.48.2

### ISSUE THREAD

**Issue by Coda-Coda** [edonet/vscode-command-runner#29]
Command runner keyboard shortcuts used to work for me, but they no longer work properly.

Pressing `ctrl+alt+1` with settings.json open results in:
```bash
% echo file 
file
```

Rather than the expected:
```bash
% echo settings.json 
settings.json
```

(The expected output above _is_ produced when running the command via `> Run Command` then selecting `echo file` from the list. It is only when using the keybinding that it doesn't work.)

-----

VSCode 1.48.2, macOS Catalina 10.15.6

settings.json
```javascript
{
  "command-runner.terminal.name": "runCommand",
  "command-runner.terminal.autoClear": true,
  "command-runner.terminal.autoFocus": true,
  "command-runner.commands": {
      "echo workspaceFolder": "echo ${workspaceFolder}",
      "echo file": "echo ${fileBasename}"
  }
}
```

keybindings.json
```javascript
[
    {
    "key": "ctrl+alt+1",
    "command": "command-runner.run",
    "args": { "command": "echo file" }
    }
]
```

**Comment by edonet** [comment]
Thank you for issues，the problem has fixed.
