### ISSUE TITLE
Assign a hotkey to a specific command

### ISSUE THREAD

**Issue by taxilian** [edonet/vscode-command-runner#3]
Is there any way to use this to assign a hotkey to a specific command?

**Comment by mn4367** [comment]
Indeed, this is a great simple extension and binding hotkeys to commands is the only thing I miss.

**Comment by edonet** [comment]
hi, You can bind custom keys for the command which defined in configuration

{
    "key": "ctrl+alt+1",
    "command": "command-runner.run",
    "args": { "command": "echo file" }
}

**Comment by mn4367** [comment]
Tried the new version and It works, thank you very much!
