### ISSUE TITLE
Default Command Does not work

### ISSUE THREAD

**Issue by bscan** [edonet/vscode-command-runner#31]
Hello! Thanks for putting this extension together, I find it very useful. 

The default settings look like a good demo of the extension, but they do not work. When a user clicks on "Edit in settings.json", the settings.json will be populated with the example command `"echo": "echo 'this is a test command: ${file}'"`.  However, when selecting "Run Command" from the editor window, nothing happens. At first, I thought the extension was broken but it turns out that the default command is excluded from the list and no message is printed to the screen or to the dev console. 

Changing to a different example command, or allowing the "echo" command would be helpful for new users testing out this extension. It might also be useful to pop-up a small error message when the user does not have any commands. 

Thanks!

![Custom](https://user-images.githubusercontent.com/10503608/103421849-7ec01200-4b6c-11eb-9f37-1fb0a72dcad8.png)

Filtering code. Can this be removed?
```
const keys = Object.keys(commands).filter(
             key => key !== 'echo' || commands[key] !== 'echo \'this is a test command: ${file}\''
        );
```

Suggested addition:
```
if (!keys.length) {
   +        vscode.window.showInformationMessage('Command Runner Error: Please add commands to your settings');
            return;
        }
```

**Comment by edonet** [comment]
Thank you for issue!
