### ISSUE TITLE
[Feature] 支持按命令执行历史排序

### ISSUE THREAD

**Issue by Higurashi-kagome** [edonet/vscode-command-runner#32]
非常好用的扩展，谢谢！

在设置了多个命令时，所有命令将按照设置的顺序在使用 `Ctrl + Shift + R` 打开的命令面板中依次排序，因为被经常执行的命令通常只是少数，所以希望能够支持按命令执行历史排序，比如上一次执行的命令在下一次打开命令面板时优先显示。

**Comment by edonet** [comment]
谢谢支持！
