### ISSUE TITLE
selectedPosition and selectedPositionList only gives start/active position

### ISSUE THREAD

**Issue by mngan** [edonet/vscode-command-runner#42]
I expected selectedPosition to give you 4 numbers, the start and end positions of the selection. Looking at the code I think the selectedPosition() should look more like this:

```
selectedPosition(): string {
        const [sl] = this.selections() || [];

        // 存在选项
        if (sl) {
            return [sl.start.line + 1, sl.start.character + 1, sl.end.line + 1, sl.end.character + 1].join(',');
        }

        // 返回空
        return '';
    },
```

Also, you use `active`. The docs say that `active` is the current cursor position. It may not necessarily be the `start` or `end` of the selection. There is also `anchor` which I think is the same as `start`. 

Perhaps this is not the usage you had intended for the selectedPosition/selectedPositionList variables?

**Comment by edonet** [comment]
Please use selectedLocation and selectedLocationList instead！
