### ISSUE TITLE
Spontaneously adding file name

### ISSUE THREAD

**Issue by Finist02** [edonet/vscode-command-runner#45]
- In version 0.0.121, when the command is invoked, the name of the current file opened in vsCode is appended. In version 0.0.120 this is not observed

Example
```json
"TrackLogs":"D:/Example/Example.exe"
```

With the 1.cs tab active, the  **D: /Example/Example.exe D: /Example/1.cs**  command will be executed

**Comment by edonet** [comment]
Thinks for issue, fixed with 0.0.122, enjoy it!

**Comment by Finist02** [comment]
Thank you, fixed

**Comment by airtonix** [comment]
It's still happening
