### ISSUE TITLE
Start a command in a new shell

### ISSUE THREAD

**Issue by robertsteilberg** [edonet/vscode-command-runner#5]
Is it possible to start a command in a new shell? I have defined several commands to run, but when I run them, they all run in the same shell, so (for instance) if one is running a server I cannot run any other commands simultaneously.

**Comment by edonet** [comment]
Now, you can customize the terminal as this to create a new terminal what you want.
{
    "key": "ctrl+alt+1",
    "command": "command-runner.run",
    "args": { "terminal": "terminalName" }
}

**Comment by CrackerKSR** [comment]
but where to put this snippet
I tried insert this after command key like this but it detects each keys as command

```bash
  "command-runner.terminal.name": "runCommand",
    "command-runner.terminal.autoClear": true,
    "command-runner.terminal.autoFocus": true,
    "command-runner.commands": {
        "Run Android"   : "npx react-native run-android",
        "Start Metro"   : "npx react-native start",
        "Log Android"   : "npx react-native log-android",
        "adb: connect"  : "adb connect 192.168.0.101",
        "adb: reverse"  : "adb reverse tcp:8081 tcp:8081",
        // "echo workspaceFolder": "echo ${workspaceFolder}",
        // "echo file": "echo ${file}",
        
    },
```

After adding shortcut like this.

```bash
  "command-runner.terminal.name": "runCommand",
    "command-runner.terminal.autoClear": true,
    "command-runner.terminal.autoFocus": true,
    "command-runner.commands": {
          {
          "key": "ctrl+alt+1",
          "command": "command-runner.run",
          "args": { "terminal": "terminalName" }
          }
    },
```

I tried different different combination to get the correct way. But description is lacking of detailing although extention is awesome and time saver.
