### ISSUE TITLE
${workspaceFolder}, ${workspaceRoot} variables don't work

### ISSUE THREAD

**Issue by aromarious** [edonet/vscode-command-runner#53]
I use this extension every day. That's how much I love it.

But I noticed `${workspaceFolder}`, `${workspaceRoot}` variables don't work now.
Not knowing the reason they can't, I want and need to use these variables.

My configuration: 
```
  "command-runner.commands": {
    "echo workspaceFolder": "echo ${workspaceFolder}",
  },
```
its execution result: 
```
echo  

$ 
```

Please could you tell me how to fix it. Thanks.

**Comment by edonet** [comment]
As the `${workspaceFolder}` is obtained from the workspace of the current project, I cannot give a clearer plan without knowing the details of your current project. 
The following is the implementation code, which may help you troubleshoot problems.
``` typescript
{ 
    workspaceFolder(): string {
        const workspace = this.workspace();
        const document = this.document();
        const workspaceFolder = (
            document ?
            workspace.getWorkspaceFolder(document.uri) :
            workspace.workspaceFolders ?
            workspace.workspaceFolders[0] :
            undefined
        );

        // 返回结果
        return workspaceFolder ? workspaceFolder.uri.fsPath : '';
    }
}
```
