### ISSUE TITLE
The activated file is appended by default to the command

### ISSUE THREAD

**Issue by ivorobioff** [edonet/vscode-command-runner#57]
It's not clear in the manual but when running a command triggered from the context menu the selected file/folder is automatically appended to the end of the command, so there's no need to write something like this `echo ${file}` and you can just write `echo`. Is this feature or bug? If it's a feature it would be nice to be able to disable it for commands not needing it.

**Comment by edonet** [comment]
Yes, the currently selected file is automatically appended to the end of the command in the context menu. For better semantics, ${selectedFile} and ${selectedFiles} were added in v0.0.124 to represent context-selected files. Also added the `autoAppendSelectedFiles` option to control whether to automatically append selected files to the command. enjoy it.
