### ISSUE TITLE
[Feature Request] preserve focus

### ISSUE THREAD

**Issue by fifv** [edonet/vscode-command-runner#58]
I find it's a demand for me to show the terminal but not focus it.
So I modified `Command.ts` like this: 
```typescript
// if (autoFocus) {
//     terminal.show();
// }
terminal.show(!autoFocus)
```
This satisfied my need. When `autoFocus === true`, terminal will be focused, while `autoFocus === false` only shows the terminal but not focus it.
I hope whether `preserveFocus` can be configured.

**Comment by edonet** [comment]
Because some users really don't want the terminal to be displayed every time they run the command, causing interference. The optimized code implementation is as follows:

``` js
if (autoFocus) { 
    terminal.show(true);
}
```
Hope it can solve your problem, enjoy it.
