### ISSUE TITLE
Rotate Image Using Command Runner

### ISSUE THREAD

**Issue by blueray453** [edonet/vscode-command-runner#59]
I have made a command like:

```
{
    "command-runner.terminal.name": "runCommand",
    "command-runner.terminal.autoClear": true,
    "command-runner.terminal.autoFocus": true,
    "command-runner.commands": {
        "Rotate Image": "convert ${file} -rotate 90 ${file}"
    }
}
```

The output is:

```
% convert  -rotate 90  "/media/ismail/Documents/primative-level-of-decomposition.png"
convert-im6.q16: no images defined `/media/ismail/Documents/primative-level-of-decomposition.png' @ error/convert.c/ConvertImageCommand/3258.
```

If you look at the command, `${file}` is two times, but the command it populates, `${file}` only appears at the end.

How can I rotate image with `convert file.jpg -rotate 90 file.jpg` [command](https://unix.stackexchange.com/a/365595/206574) using Command Runner extension.

One more thing, is there any way to run the command without opening the terminal?

**Comment by blueray453** [comment]
Just to be clear, I selected the image from (left side) file viewer. Right Click the Image. Then `Run Command`. Then select the command.

**Comment by edonet** [comment]
When executing a command from the context menu, the selected file is automatically appended to the end of the command. And ${file} means the currently active file, not the selected file, so your command will not do what you expect.
In the v0.0.124 version, ${selectedFile} and ${selectedFiles} are specially added to meet your needs. You can try `convert ${selectedFile} -rotate 90 ${selectedFile}`, enjoy it.
