### ISSUE TITLE
Problem with whitespace in path for ${file}

### ISSUE THREAD

**Issue by akej74** [edonet/vscode-command-runner#6]
Hi, thanks for this useful extension. I'm having a problem using ${file} when the path contains a whitespace. 

Example:
- File is located in `G:\Google Drive\Python\test.py`
- ${file} returns `G:\Google\ Drive\Python\test.py`

I.e. the space is escaped with a backslash and this causes problems when I try to run a specific command on the file. This is on a Windows environment.

Example of what I'm working on (PyQT, for building a Python class from UI XML file):
```
    "command-runner.commands": {
        "Run PyUIC": "pyuic5.exe --from-imports ${file} -o ${fileBasenameNoExtension}.py"
```

**Comment by edonet** [comment]
Thanks for your issue! This extension no longer escapes paths. Please use quotation marks to wrap paths when it includes whitespace, as `cat "${file}"`.

**Comment by akej74** [comment]
Thanks for the update, works nicely!
