### ISSUE TITLE
Pass parameter to commands

### ISSUE THREAD

**Issue by simbo1905** [edonet/vscode-command-runner#9]
I would like to set something like:

```
git show --name-only ${1}
```

Where I can pass a commit sha as the first positional parameter. Being able to use ${2} up to ten would be really helpful.

**Comment by denishowew** [comment]
Where do you want the values for these parameters to come from?

**Comment by BigSeb** [comment]
I would suggest using an InputBox (here: [https://code.visualstudio.com/api/references/vscode-api#window.showInputBox](url)). This is similar in approach to what the ${command:SpecifyScriptArgs} command from Powershell Extension is doing.

Maybe the input box could be displayed automatically when a positional parameter or a different variable is defined in the command.

**Comment by edonet** [comment]
Thanks for issue. Now, you can pass parameter to commands with `${input:defaultValue}`.  Also if you have any other opinions, please let me know.
